
# PPO config file
lr: 0.001
max_grad_norm: 1.0

frames_per_batch: 1024 # training batch size
total_frames: 1000000 # total frames collected

sub_batch_size: 128  # cardinality of the sub-samples gathered from the current data in the inner loop
num_epochs: 16  # optimization steps per batch of data collected
clip_epsilon: 0.2  # clip value for PPO loss: see the equation in the intro for more context.

gamma: 0.99
lambda: 0.95
entropy_eps: 0.1 #0.0001